### ISSUE TITLE
hmm search results not included in phate_sequenceAnnotation_main.gff

### ISSUE THREAD

**Issue by thr44pw00d** [carolzhou/multiPhATE#10]
Hi,
I'm not sure if this is intended... I run multiphate using phanotate for gene calling, and for annotation only pvogs_hmm. I get hits from the hmm search, which are saved in the directory PipelineOutput/mydir/HMM/Protein/. However, these hits are not included in the file phate_sequenceAnnotation_main.gff. Would there be a way to include them there?

Thank you!

**Comment by carolzhou** [comment]
Please send me your config file, your phate_sequenceAnnotation_main.out and .gff files.

Sent from my iPhone

On Oct 21, 2019, at 8:20 AM, thr44pw00d <notifications@github.com> wrote:

﻿

Hi,
I'm not sure if this is intended... I run multiphate using phanotate for gene calling, and for annotation only pvogs_hmm. I get hits for the proteins of my genome, which are saved in the directory PipelineOutput/test2/HMM/Protein/. However, these hits are not included in the file phate_sequenceAnnotation_main.gff. Would there be a way to include these hits there?

Thank you!

**Comment by thr44pw00d** [comment]
[multiphate.zip](https://github.com/carolzhou/multiPhATE/files/3760832/multiphate.zip)

**Comment by carolzhou** [comment]
The hmm search results should now appear in the gff-formatted output.

**Comment by thr44pw00d** [comment]
Great, it worked, thanks a lot!
