### ISSUE TITLE
CGC_parser.py -- SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?

### ISSUE THREAD

**Issue by asttra** [carolzhou/multiPhATE#11]
I had to go into the CGC_parser.py file and fix multiple syntax errors (I think I fixed about four lines of code). 

`/projects/nanopore-working/niki/bin/multiPhATE/CompareCalls//CGC_parser.py:294: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  OUT.write("%s\n" ("ERROR encountered: unknown strand designator\n"))
/projects/nanopore-working/niki/bin/multiPhATE/CompareCalls//CGC_parser.py:296: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  USER_OUT.write("%s\n" ("ERROR encountered: unknown strand designator\n"))`

Edits are in bold:
OUT.write("%s\n" **%** ("ERROR encountered: unknown strand designator\n"))
USER_OUT.write("%s\n" **%** ("ERROR encountered: unknown strand designator\n"))

**Comment by carolzhou** [comment]
Thank you for pointing this out. Those lines of code are invoked when there is unexpected input from glimmer, providing a warning to the user. Unfortunately that was never encountered in my testing. The syntax errors should be corrected now. Please do let me know if you notice any further anomalies. Thank you for using multiPhATE.
