### ISSUE TITLE
GFF3 format doesn't seem right 

### ISSUE THREAD

**Issue by Calvinblue** [carolzhou/multiPhATE#13]
Dear Carol, 

I have the latest update of Multiphate and I have some trouble opening the annotation.main.gff file with softwares such as Mauve, Artemis,  Ugene, as they produce erros such as : 

UGENE : [12:51:49] 'Loading documents' task failed: Subtask {Opening view for document: phate_sequenceAnnotation_main.gff} is failed: Subtask {Load document: 'phate_sequenceAnnotation_main.gff'} is failed: Parsing error: incorrect attributes field  annot13=(homology) blastp RecName: Full=Endonuclease MutS2 at line 6

Do you have any idea how I could go around this issue ? Also if I may suggest two features that could be added in the next release : 
-> It would be nice if an option was added to control the number of cores that the analysis runs on, for now I have manually edited your script ton increase the cpu number of blast and it seems to improve the pipeline's performance.
-> Could you also add a gbk output? it would be easier to submit the annotated genome to sequence database afterwards

Thanks a lot for that wonderful software and for your help ! 

Best regards,

Antoine

**Comment by carolzhou** [comment]
Thank you for your helpful suggestions, Antoine.

Please send me the line of code in which you modified the blast call to set the option to specify the number of cores, as that will assist me in arranging to include that option in the user config file in a future release.

Please also send me your .gff output file that causes errors as input to the third party codes, or if quite large, a segment of that file that generates errors will do. I tested the gff output using an online gff format checker, and the output passed, but as I do not routinely use the third part programs you mention, I appreciate your identification of these format problems. There could also be something about your data that differs from mine, so it will be interesting to see whether my code interpreted your data correctly.

I appreciate your input, and thank you for using multiPhATE.

Data file can be sent directly to zhou4@llnl.gov.

Sincerely,
-Carol Zhou

Sent from my iPhone

On Jan 8, 2020, at 3:58 AM, Calvinblue <notifications@github.com> wrote:

﻿

Dear Carol,

I have the latest update of Multiphate and I have some trouble opening the annotation.main.gff file with softwares such as Mauve, Artemis, Ugene, as they produce erros such as :

UGENE : [12:51:49] 'Loading documents' task failed: Subtask {Opening view for document: phate_sequenceAnnotation_main.gff} is failed: Subtask {Load document: 'phate_sequenceAnnotation_main.gff'} is failed: Parsing error: incorrect attributes field annot13=(homology) blastp RecName: Full=Endonuclease MutS2 at line 6

Do you have any idea how I could go around this issue ? Also if I may suggest two features that could be added in the next release :
-> It would be nice if an option was added to control the number of cores that the analysis runs on, for now I have manually edited your script ton increase the cpu number of blast and it seems to improve the pipeline's performance.
-> Could you also add a gbk output? it would be easier to submit the annotated genome to sequence database afterwards

Thanks a lot for that wonderful software and for your help !

Best regards,

Antoine

**Comment by Calvinblue** [comment]
Hi Carol, 
I have another feature suggestion : could you add the scores (e value, %identity, %coverage) for HMM and blastp results in the output GFF ? This would help a lot choosing between different annotations when the different annotation tools do not provide coherent results.

Thank you very much :)

Antoine

**Comment by carolzhou** [comment]
Thank you for all of your helpful suggestions, Antoine. Because the last column of GFF is a dump of so much information, I opted to abbreviate the annotations somewhat, but I agree with you that the % identity etc. really should be there. It's on my list for improving the code. As we discussed about the GFF formatting, again thank you for testing Prokka's output, which generates the same errors when it's GFF output is input to Artemis. I do believe the GFF is correct based on the GFF3 specification, but if you find any other problems, please do alert me.
