### ISSUE TITLE
Last protein annotations missing

### ISSUE THREAD

**Issue by bognabognabogna** [carolzhou/multiPhATE#14]
Dear Carol,

I have been using multiPhaTE for a couple of months and I find it pretty useful. Thank you for sharing the code!
I have recently discovered one peculiarity, namely a missing line for the last protein in the genome.
While the file phate_phanotate.gff contains all ORFs the file
phate_sequenceAnnotation_main.gff misses the last ORF from the phate_phanotate.gff file.

I am not sure if it is due to some code / genome or config issues.
Would you please have a look?

**Comment by Chrisjrt** [comment]
I've noticed this issue too. The annotations are in the annotation directories (e.g. the Blast/Protein/ or HMM/Protein/) but just hasn't seemed to make it into the phate_sequenceAnnotation_main.gff file.

**Comment by carolzhou** [comment]
This issue has been repaired. Now the final protein data line is being included in the GFF output file, phate_sequenceAnnotation_main.gff.

**Comment by bognabognabogna** [comment]
That's great. Thank you Carol!
