### ISSUE TITLE
Issue with Phanotate: Output Files Empty/Missing 

### ISSUE THREAD

**Issue by sgsutcliffe** [carolzhou/multiPhATE#16]
Hello,

I ran multiPhate on the sample file for Lambda:
Gene-calling (followed by translation) with phanotate and glimmer. 

My output files for glimmer seem okay, I put empty by the files that are empty. What I have is:
glimmer.coords
glimmer.detail
glimmer.icm
glimmer.longorfs
glimmer.predict
glimmer.train
Lambda.config
phate_genecallPhage.log
phate_sequenceAnnotation_main.gff
phate_sequenceAnnotation_main.log
phate_sequenceAnnotation_main.out **(Empty)**
results.txt **(Empty)**
runPhaTE.log

In my phate_sequenceAnnotation_main.log I got an error;
fileError [Errno 2] No such file or directory: '/Users/steven/Bioinformatics/multiPhATE-master/PipelineOutput/Lambda/phanotate.cgc' gene call file, /Users/steven/Bioinformatics/multiPhATE-master/PipelineOutput/Lambda/phanotate.cgc

So I made sure Phanotate had installed properly, by running the test file they suggest on Github:
./phanotate.py tests/NC_001416.1.fasta

That worked.

Lastly, I checked phate_genecallPhage.log
The last three lines are:
Processing Glimmer complete.
Not running GeneMarkS gene calling
Processing PHANOTATE

Nothing comes after PHANOTATE.

Is it just a problem with Phanotate? I would like to use Phanotate, but if it is the only part that is broken I may move on to the other steps to see if they work.

Thanks,
Steven

**Comment by sgsutcliffe** [comment]
I was able to figure it out. It was an issue with the directory I had for Phanotate, and also I did not set up the Fastpath for Phanotate.

**Comment by carolzhou** [comment]
Great! I’m glad you got that figured out. Thank you for your interest in multiPhATE. Let me know if you have any other difficulties.

Sent from my iPhone

On Feb 25, 2020, at 7:47 AM, sgsutcliffe <notifications@github.com> wrote:

﻿

I was able to figure it out. It was an issue with the directory I had for Phanotate, and also I did not set up the Fastpath for Phanotate.
