### ISSUE TITLE
Error while configuring annotation

### ISSUE THREAD

**Issue by outbig** [carolzhou/multiPhATE#17]
Dear Carol, 

I am installing the multiPhATE on my workstation step by step. Mutiple gene callers were sucessfully installed and working perfectly.  But, I have gotton a error mesage saying below while configuring annotation. I have concatenated the viral.1.protein.faa,  viral.2.protein.faa, and  viral.3.protein.faa to viral.protein.faa and specified the file path in the multiPhATE.config. Please let me know how to address it. Thanks in advance. Looking forward to hearing from you asap

Best, 
Yongkyu

BLAST Database error: No alias or index file found for protein database [/home/ykim/software/multiPhATE-master/Databases/NCBI/Virus_Protein/viral.protein.faa] in search path [/home/ykim/software/multiPhATE-master::]

**Comment by carolzhou** [comment]
My first thought would be that you need to run makeblastdb to format the database for blast. Please try that and let me know if it solves the problem.

Sent from my iPhone

On Mar 23, 2020, at 2:14 AM, Yongkyu Kim <notifications@github.com> wrote:

﻿

Dear Carol,

I am installing the multiPhATE on my workstation step by step. Mutiple gene callers were sucessfully installed and working perfectly. But, I have gotton a error mesage saying below while configuring annotation. I have concatenated the viral.1.protein.faa, viral.2.protein.faa, and viral.3.protein.faa to viral.protein.faa and specified the file path in the multiPhATE.config. Please let me know how to address it. Thanks in advance. Looking forward to hearing from you asap

Best,
Yongkyu

BLAST Database error: No alias or index file found for protein database [/home/ykim/software/multiPhATE-master/Databases/NCBI/Virus_Protein/viral.protein.faa] in search path [/home/ykim/software/multiPhATE-master::]

**Comment by outbig** [comment]
Thank you Carol. It's workding!

**Comment by carolzhou** [comment]
Thank you for using multiPhATE.

Sent from my iPhone

On Mar 23, 2020, at 3:50 PM, Yongkyu Kim <notifications@github.com> wrote:

﻿

Thank you Carol. It's workding!
