### ISSUE TITLE
Problem with getDBs.py and RefSeq and Swissprot file formats

### ISSUE THREAD

**Issue by pinetr33z** [carolzhou/multiPhATE#18]
Hi Carol, 

I'm setting up my databases to run multiPhATE but it seems that the getDBs.py script is having problems with the file formats that are being downloaded from NCBIs RefSeq and Swiss prot databases. 

These are several of the errors appearing
`gzip: ls.out: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

gzip: refseq_protein.00.phr: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

gzip: refseq_protein.00.pin: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors`

When I look at the contents of some of the directories I see these types of files
`ls.out         swissprot.phr  swissprot.pog  swissprot.pot  swissprot.ppi  swissprot.ptf  swissprot.tar.gz      taxdb.btd
swissprot.pdb  swissprot.pin  swissprot.pos  swissprot.ppd  swissprot.psq  swissprot.pto  swissprot.tar.gz.md5  taxdb.bti`

The getDBs.py script cant process these files. 

Any ideas/suggestions?
Thanks!

**Comment by carolzhou** [comment]
Hi pinetr33z:

When I wrote getDBs.py, the blast updater (update_blast.pl) was downloading a packed file containing the data files. It looks as though now it is downloading the unpacked files, and getDBs.py is unnecessarily trying to unpack them. If that is the case, then you have what you need, and the getDBs.py script will need to be updated to reflect changes at the data source. Thank you for bringing this to my attention. If this does not address the problem you are seeing, please feel free to contact me again.

Sincerely,
-Carol Zhou

**Comment by pinetr33z** [comment]
Hi Carol, 

Thanks for the clarification. In that case are the unpacked files already in a Blast database format? When writing the multiPhATE.config file does the path to the databases need to include all the files or just the directory that they are located in?

Thanks!
Justin Bishop

**Comment by carolzhou** [comment]
The path should indicate the full directory path plus the filename of the database. For example, /Users/me/myMultiPhateDirectory/Databases/Swissprot/swissprot

From there, blast knows to access the files that have the expected extensions, and for the really big databases (e.g., NR), it will iterate through the files that are numbered (e.g., 01, 02…).

I hope that helps.
-Carol

**Comment by pinetr33z** [comment]
Hi Carol, 
I got the pipeline to run but there were still issues with the databases. 
The RefSeq and Swissprot databases are missing index files. I was able to download the Swissprot database in FASTA format using the FPT and format the files into a Blastable format manually but Im not able to do that with the RefSeq files. In the end I excluded the RefSeq databases. 

Thanks!
Justin

**Comment by carolzhou** [comment]
I suspect things may have changed at NCBI with respect to exactly what is loaded on their ftp interface. I will test drive the downloaded script and update it accordingly. It was provided as a convenience, and one can always do the downloading and blast formatting manually. Thank you for bringing to my attention the issues with getDBs.py, and thank you for your interest in multiPhATE. -Carol

Sent from my iPhone

On Apr 10, 2020, at 9:09 AM, pinetr33z <notifications@github.com> wrote:

﻿

Hi Carol,
I got the pipeline to run but there were still issues with the databases.
The RefSeq and Swissprot databases are missing index files. I was able to download the Swissprot database in FASTA format using the FPT and format the files into a Blastable format manually but Im not able to do that with the RefSeq files. In the end I excluded the RefSeq databases.

Thanks!
Justin

**Comment by carolzhou** [comment]
I think most of the issues with the database downloader script have been addressed, except that the swissprot and Refseq Protein databases are not being recognized by blastp. Strange, since it is the update script from blast+ that I am using to download these databases. Otherwise, the new script, dbPrep_getDBs.py, seems to be working pretty well to assist in downloading the databases. Let me know if any further issues are found.

**Comment by carolzhou** [comment]
The blast+ downloaded using Conda recognizes only the Swissprot database downloaded from Uniprot. At this time I now suggest switching to multiPhATE2, and using the dbPrep_getDBs.py script in that repository to download and install supporting databases.
