### ISSUE TITLE
need to modify getDBs.py ?

### ISSUE THREAD

**Issue by carolzhou** [carolzhou/multiPhATE#19]
Check performance of getDBs.py due to possible changes in NCBI's files on their ftp server.

**Comment by nikolasbasler** [comment]
Hello. Not sure if I should add this here but I noticed something else with the getDBs.py: In the documentation you state that the files containing the virus genomes should be concatenated into one and then made into a blast database. However, getDBs.py creates separate databases for both files (this is also the case for the proteins). 
Also, one of the calls that should create a protein database attempts to make a nucl blast database, which leads to thousands of error messages.
I attached a screenshot where all of the above is visible.
<img width="1440" alt="multiphate" src="https://user-images.githubusercontent.com/44873904/81963451-63bc8400-9615-11ea-8344-2fd3190b0ce4.png">

**Comment by carolzhou** [comment]
The database downloader script has been updated, now called:  dbPrep_getDBs.py. I'm still having difficulty getting blastp in Conda to recognize the Swissprot and Refseq Protein databases, although the hmm search codes (eg, phmmer, jackhmmer) recognize those databases just fine. I will post further updates as I get these glitches worked out.

**Comment by carolzhou** [comment]
The dbPrep_getDBs.py script included in the multiPhATE2 distribution has been updated and tested and is working in my hands as of this writing (26 Jan2021). One is advised to switch to multiPhATE2 at this time, as multiPhATE will soon be deprecated.
