### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object while running blast

### ISSUE THREAD

**Issue by ShailNair** [carolzhou/multiPhATE#22]
Hi,
I got the following error while running blast
phate_sequenceAnnotation_main says, Running Blast against phage genome database(s)...
phate_blast says, Running NCBI blast: /home/mcs/soft/multiphate/Databases/NCBI/Virus_Genome/ncbiVirusGenomes.fasta ncbi
Warning: [blastn] Examining 5 or more matches is recommended
Traceback (most recent call last):
  File "/home/mcs/soft/multiphate/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 721, in <module>
    blast.runBlast(myGenome.contigSet,'genome')
  File "/home/mcs/soft/multiphate/SequenceAnnotation/phate_blast.py", line 552, in runBlast
    self.blast1fasta(fasta,outfile,database,dbName)
  File "/home/mcs/soft/multiphate/SequenceAnnotation/phate_blast.py", line 459, in blast1fasta
    newAnnotation.link2databaseIdentifiers(database,dbName) # Get DBXREFs, packed into self.description
  File "/home/mcs/soft/multiphate/SequenceAnnotation/phate_annotation.py", line 476, in link2databaseIdentifiers
    taxonList = self.getNCBItaxonomyID(ncbi_taxon_lookup)
  File "/home/mcs/soft/multiphate/SequenceAnnotation/phate_annotation.py", line 422, in getNCBItaxonomyID
    match_taxID = re.search(p_taxID,out)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
phate_runPipeline says, sequence annotation processing complete.
phate_runPipeline says, code completed at 2020-09-28 17:51:24.457469

I have attached full log
[log.txt](https://github.com/carolzhou/multiPhATE/files/5291609/log.txt)

**Comment by carolzhou** [comment]
Hi multiPhATE user:

Your genome file name may be a problem. I suggest removing all special characters from the filename. For example, you have ‘-‘ and ‘[‘ in the filename.  Rename it something like, Galaxy22_SI_phage_sequence.fasta.

Also you might run your fasta file through the cleanHeaders.py, as your fasta headers might also have special characters.

3rd party codes may choke when encountering odd characters. It is best to use only alpha-numeric in filenames and fasta headers.

Regarding the blast warning about 5 or more matches, this is a warning that the more recent versions of blast are returning if the user specifies fewer than 5 hits. This message is annoying, but can be ignored; or, you can set your number of hits to 5 or more, and the warning will go away.

Please give the above a try, and do let me know if you encounter any other issues.

Thank you for your interest in multiPhATE.

-Carol Zhou

**Comment by carolzhou** [comment]
It looks as though gene finding failed for all but Prodigal, and since you selected PHANOTATE as the preferred gene caller, the code did not generate gene and protein files. Check for these in PipelineOutput/myGenome/gene.fnt,protein.faa. Your computer is returning error messages that it cannot find the folder or cannot find the code. Also, PHANOTATE is failing because it cannot find fastpathz. You may need to install fastpathz manually. Given these errors, I doubt that the sequence annotation will be able to run. Please slow down:  set translate_only='true' in your configuration file. Then, test each gene finder one at a time. When that works, then run one of the sequence annotation processes to test that. It will be best to start with one of the smaller databases (e.g., Phamtome, not NR!).

**Comment by ShailNair** [comment]
I had called all gene callers one by one on my personal computer as I could not install some of the third party software on the main server (requires sudo option which i do not have). Once i got all the files, i transferred onto the PipelineOutput folder on server-side and went on with the annotation. Is that workable or i need to run all processes on the same computer?

I will try with the steps you have given. will update soon.

Thanks,

**Comment by carolzhou** [comment]
Hi Shail,

This will work if you are running multiPhATE2, downloaded from https://github.com/carolzhou/multiPhATE2/.  You will need to run the gene callers within that code (set translate_only=’true’). Then, you may copy over the entire contents of the genome’s output subdirectory (from PipelineOutput/) on your personal computer, into the PipelineOutput/ folder on the main server.

Using multiPhATE2, you can then set a checkpoint (checkpoint_phate=’true’), and the code should pick up the gene-call data and run the functional annotations.

This plan will not work with the original multiPhATE. Checkpoints are a feature that were added to multiPhATE2.

I hope that helps.
-Carol

**Comment by ShailNair** [comment]
Thanks. I will try with multiphate2
