### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found and Unrecognized database: refseqGene

### ISSUE THREAD

**Issue by dwightkuo** [carolzhou/multiPhATE#5]
I get an xml.etree.ElementTree.ParseError: no element found: line 1, column 0 error when running multiPhATE on the included example. I also get a refseqGene warning. See below...An additional question is about accession2taxid. I don't see this in the example multiphate.config file. How is this specified / used in the software?
```
WARNING in annotation module: Unrecognized database: refseqGene
Blast module says: removing raw data files.
Sequence annotation main says: Gene blast complete.
Sequence annotation main says: Preparing for protein blast...
Sequence annotation main says: Running Blast against protein database(s)...
Blast module says: Running NCBI_VIRUS_PROTEIN blast: /sc1/groups/md/RMS/Data/reference_genomes/NCBI/viral.1.protein.faa ncbiVirusProtein
Blast module says: Running PHANTOME blast: /sc1/groups/md/RMS/sw/multiPhATE/Databases/Phantome/Phantome_Phage_genes.faa phantome
Traceback (most recent call last):
  File "/home/kuop/multiPhATE/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 794, in <module>
    blast.runBlast(myGenome.proteinSet,'protein')
  File "/home/kuop/multiPhATE/SequenceAnnotation/phate_blast.py", line 588, in runBlast
    self.blast1fasta(fasta,outfile,database,dbName)
  File "/home/kuop/multiPhATE/SequenceAnnotation/phate_blast.py", line 334, in blast1fasta
    tree.parse(outfile)
  File "/sc1/groups/md/RMS/sw/miniconda2/envs/multiphate/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
Gene caller has been set to: phanotate

```

multiphate.config file:
```
Genome List:
Genome 1
genome_file='P2.fasta'
genome_type='phage'
species='P2_phage'
name='P2'
output_subdir='P2/'
Genome 2
genome_file='Lambda.fasta'
genome_type='phage'
species='Lambda_phage'
name='Lambda'
output_subdir='Lambda/'
END of list
genetic_code='11'
translate_only='false'
gene_caller='phanotate'
genemarks_calls='false'
prodigal_calls='false'
glimmer_calls='false'
prodigal_calls='true'
glimmer_calls='true'
phanotate_calls='true'
ncbi_virus_blast='true'
refseq_gene_blast='true'
phantome_blast, pvogs_blast
ncbi_virus_protein_blast='true'
kegg_virus_blast='false'
phantome_blast='true'
pvogs_blast='false'
swissprot_blast='true'
refseq_protein_blast='false'
nr_blast='false'
blast_identity='60'
blastp_hit_count='3'
blastn_hit_count='3'
hmm_program='jackhmmer'
pvogs_hmm='false'

ncbi_virus_database='/sc1/groups/md/RMS/Data/reference_genomes/NCBI/viral.1.1.genomic.fna'
refseq_gene_database='/sc1/groups/md/RMS/Data/blastDB/current/refseqgene'
ncbi_virus_protein_database='/sc1/groups/md/RMS/Data/reference_genomes/NCBI/viral.1.protein.faa'
phantome_database='/sc1/groups/md/RMS/sw/multiPhATE/Databases/Phantome/Phantome_Phage_genes.faa'
pvogs_database='/sc1/groups/md/RMS/sw/multiPhATE/Databases/pVOGs/pVOGs.faa'
swissprot_database='/sc1/groups/md/RMS/Data/blastDB/current/swissprot'
refseq_protein_database='/sc1/groups/md/RMS/Data/blastDB/current/refseq_protein'
nr_database='/sc1/groups/md/RMS/Data/blastDB/current/nr'

phate_warnings='true'
phate_messages='true'
phate_progress='true'
cgc_warnings='true'
cgc_messages='true`'
cgc_progress='true'
clean_raw_data='true'

```

**Comment by carolzhou** [comment]
Thank you for using multiPhATE.  I have been on extended leave from work, and just now found your email.  I will look into this error and respond shortly. -Carol Zhou

**Comment by carolzhou** [comment]
As long as the accession2taxid is resident in the same directory as the fasta data file, the code will find it. You do not have to specify the location in the config file.

Looking into the other issues....

Sent from my iPhone

On Jul 22, 2019, at 12:49 PM, dwightkuo <notifications@github.com<mailto:notifications@github.com>> wrote:


I get an xml.etree.ElementTree.ParseError: no element found: line 1, column 0 error when running multiPhATE on the included example. I also get a refseqGene warning. See below...An additional question is about accession2taxid. I don't see this in the example multiphate.config file. How is this specified / used in the software?

WARNING in annotation module: Unrecognized database: refseqGene
Blast module says: removing raw data files.
Sequence annotation main says: Gene blast complete.
Sequence annotation main says: Preparing for protein blast...
Sequence annotation main says: Running Blast against protein database(s)...
Blast module says: Running NCBI_VIRUS_PROTEIN blast: /sc1/groups/md/RMS/Data/reference_genomes/NCBI/viral.1.protein.faa ncbiVirusProtein
Blast module says: Running PHANTOME blast: /sc1/groups/md/RMS/sw/multiPhATE/Databases/Phantome/Phantome_Phage_genes.faa phantome
Traceback (most recent call last):
  File "/home/kuop/multiPhATE/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 794, in <module>
    blast.runBlast(myGenome.proteinSet,'protein')
  File "/home/kuop/multiPhATE/SequenceAnnotation/phate_blast.py", line 588, in runBlast
    self.blast1fasta(fasta,outfile,database,dbName)
  File "/home/kuop/multiPhATE/SequenceAnnotation/phate_blast.py", line 334, in blast1fasta
    tree.parse(outfile)
  File "/sc1/groups/md/RMS/sw/miniconda2/envs/multiphate/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
Gene caller has been set to: phanotate



multiphate.config file:

Genome List:
Genome 1
genome_file='P2.fasta'
genome_type='phage'
species='P2_phage'
name='P2'
output_subdir='P2/'
Genome 2
genome_file='Lambda.fasta'
genome_type='phage'
species='Lambda_phage'
name='Lambda'
output_subdir='Lambda/'
END of list
genetic_code='11'
translate_only='false'
gene_caller='phanotate'
genemarks_calls='false'
prodigal_calls='false'
glimmer_calls='false'
prodigal_calls='true'
glimmer_calls='true'
phanotate_calls='true'
ncbi_virus_blast='true'
refseq_gene_blast='true'
phantome_blast, pvogs_blast
ncbi_virus_protein_blast='true'
kegg_virus_blast='false'
phantome_blast='true'
pvogs_blast='false'
swissprot_blast='true'
refseq_protein_blast='false'
nr_blast='false'
blast_identity='60'
blastp_hit_count='3'
blastn_hit_count='3'
hmm_program='jackhmmer'
pvogs_hmm='false'

ncbi_virus_database='/sc1/groups/md/RMS/Data/reference_genomes/NCBI/viral.1.1.genomic.fna'
refseq_gene_database='/sc1/groups/md/RMS/Data/blastDB/current/refseqgene'
ncbi_virus_protein_database='/sc1/groups/md/RMS/Data/reference_genomes/NCBI/viral.1.protein.faa'
phantome_database='/sc1/groups/md/RMS/sw/multiPhATE/Databases/Phantome/Phantome_Phage_genes.faa'
pvogs_database='/sc1/groups/md/RMS/sw/multiPhATE/Databases/pVOGs/pVOGs.faa'
swissprot_database='/sc1/groups/md/RMS/Data/blastDB/current/swissprot'
refseq_protein_database='/sc1/groups/md/RMS/Data/blastDB/current/refseq_protein'
nr_database='/sc1/groups/md/RMS/Data/blastDB/current/nr'

phate_warnings='true'
phate_messages='true'
phate_progress='true'
cgc_warnings='true'
cgc_messages='true`'
cgc_progress='true'
clean_raw_data='true'

**Comment by carolzhou** [comment]
There are a couple of issues with your config file.  1) You have repeated the prodigal and glimmer settings, first setting them to 'false', and then re-setting them to 'true'. In itself, this should not cause an error, but the code will interpret the last setting (ie, in this case prodigal and glimmer will be set to 'true'), and this might produce a result you did not expect. 2) you have combined the settings for Phantome, pvogs, and ncbi_virus_protein_blast, separating them by commas. Each setting needs to be listed separately and on a separate line of text; so, you need to split these out: phantome_blast='true'(carriage return)pvogs_blast='true'(carriage return) etc. Regarding the refseqGene error, there is a discrepancy between spelling of refseqGene/refseqgene. Please double-check the spelling of refseqG/gene in your path.  Please if you could correct these errors first (in the config file) and then re-run the code, it is possible that other errors might not occur. Then we can go from there if the code is still not working for you.

**Comment by dwightkuo** [comment]
Hi Carol,

I fixed issue 1). Issue 2) was a mistake on my part in copy and pasting the
config file (that line was originally part of a comment line that got
wrapped so I missed deleting the end when pasting). The refseqgene I used
looks to be correct:

[kuop@lb021login multiPhATE]$ ls
> /sc1/groups/md/RMS/Data/blastDB/current/refseqgene*
> /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nhr
>  /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nog
> /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nin
>  /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nsd
> /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nnd
>  /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nsi
> /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nni
>  /sc1/groups/md/RMS/Data/blastDB/current/refseqgene.nsq
> [kuop@lb021login multiPhATE]$


I've attached my multiphate config file as well as the full output. Let me
know if there's anything else you can think of

Thanks for your help!

Dwight

**Comment by carolzhou** [comment]
My refseqgene file list also contains files that end in .naa, .nab, and .nac.  I don't know whether this makes a difference. Maybe blast is looking for one of these files and not finding it? Please try downloading refseqgene again from NCBI and see if these other files are present. You should be able to download using getDBs.py, or manually.
