### ISSUE TITLE
GFF3 files are not GFF3 format

### ISSUE THREAD

**Issue by JessF298** [carolzhou/multiPhATE#8]
Hello,
Thank you for creating such an innovative pipeline.
I have ran multiPhATE on my genomes, using glimmer, prodigal and phanotate, and noticed that the gff files from the gene callers and the annotation file are not gff3 format. 
Using the GFF3 onlne validator on the files throws an error as there are only 8 columns instead of 9, and adding in an extra column for the score then throws an error that CDS is not a valid type.
The only errors I got in the output files are:
PSAT_file is unknown - phate_runPipeline.log

I'm not sure where this error could have occured, please can you advise?

Many thanks
Jess

**Comment by carolzhou** [comment]
Dear Jessalyn,

I am now repairing the gff formatter and will post the new code to github soon. Regarding the “PSAT_file is unknown” error, I will check to see why this error is being generated; it should not be triggered. Let me know if that error caused malfunction, but I think the code should have simply skipped over that issue.

-Carol

**Comment by carolzhou** [comment]
The GFF formatting has been repaired. Do let me know if anything looks amiss.
