### ISSUE TITLE
syntax error on sample config

### ISSUE THREAD

**Issue by bognabognabogna** [carolzhou/multiPhATE#9]
Hello,
Thank you for sharing this pipeline, it seems to be able to solve all of my problems ;-)
I am trying to run it on the sample config file, however, I get a vey similar error (see below) to the one reported in one of the closed issues (https://github.com/carolzhou/multiPhATE/issues/7).

I have included to following command in the script: print(sys.version)
to make sure I use the right python version (which was the solution for the previous issue) and it is indeed python 3.7.4.

Do you happen to know how to fix this issue?
Best wishes 
Bogna

**>> python3 multiPhate.py sample.multiPhate.config**
_3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Checking files...
Configuration complete.
Preparing to run genecall module...
Calling the gene-call module.
  File "/Users/bognasmug/Applications/multiPhATE/multiPhATE-master/GeneCalling/phate_genecallPhage.py", line 416
    print(fileType, ": ", files[fileType], end=' ')
                                              ^
SyntaxError: invalid syntax
Done!
Preparing command strings for homology searches...
Calling the sequence annotation module.
Traceback (most recent call last):
  File "/Users/bognasmug/Applications/multiPhATE/multiPhATE-master/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 87, in <module>
    import phate_fastaSequence  # generic fasta sequence module
  File "/Users/bognasmug/Applications/multiPhATE/multiPhATE-master/SequenceAnnotation/phate_fastaSequence.py", line 426
    print("Codon start locations:", end=' ')_

**Comment by carolzhou** [comment]
Yes, that is an error that occurs under Python 2.x. It should not be happening under 3.x. I will do some more testing.

Sent from my iPhone

On Oct 15, 2019, at 7:39 AM, bognabognabogna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Thank you for sharing this pipeline, it seems to be able to solve all of my problems ;-)
I am trying to run it on the sample config file, however, I get a vey similar error (see below) to the one reported in one of the closed issues (#7<https://github.com/carolzhou/multiPhATE/issues/7>).

I have included to following command in the script: print(sys.version)
to make sure I use the right python version (which was the solution for the previous issue) and it is indeed python 3.7.4.

Do you happen to know how to fix this issue?
Best wishes
Bogna

>> python3 multiPhate.py sample.multiPhate.config
3.7.4 (default, Sep 7 2019, 18:27:02)
[Clang 10.0.1 (clang-1001.0.46.4)]
Checking files...
Configuration complete.
Preparing to run genecall module...
Calling the gene-call module.
File "/Users/bognasmug/Applications/multiPhATE/multiPhATE-master/GeneCalling/phate_genecallPhage.py", line 416
print(fileType, ": ", files[fileType], end=' ')
^
SyntaxError: invalid syntax
Done!
Preparing command strings for homology searches...
Calling the sequence annotation module.
Traceback (most recent call last):
File "/Users/bognasmug/Applications/multiPhATE/multiPhATE-master/SequenceAnnotation/phate_sequenceAnnotation_main.py", line 87, in
import phate_fastaSequence # generic fasta sequence module
File "/Users/bognasmug/Applications/multiPhATE/multiPhATE-master/SequenceAnnotation/phate_fastaSequence.py", line 426
print("Codon start locations:", end=' ')

**Comment by rmostowy** [comment]
Hi,

I have the same issue and I have executed the command using python 3.7.4
`python3 multiPhate.py multiPhate.config`
However, the `python` command points to the version 2.7.10. Could it be that the main code relies on the `python` command, hence causing the version problem?

Rafal

**Comment by carolzhou** [comment]
Yes, I think this is the problem. There are two ways around this, currently:  1) You can run the code in a Conda environment that is set up to run Python 3.x. In this way, the driver code and all subordinate processing will be executed under Python 3.x. 2) You can identify (via grep) all of the lines of code that perform “python ….” and change those to “python3 ….”.  I recommend fix #1, as it is never a good idea to be modifying the code.  In a future release I can insert code to auto-detect the default python version. This is not something I had anticipated, since I’m now using Conda environments, as this is the easiest and most convenient way to manage various codes that depend on different versions of Python and other tools.

Thank you for using multiPhATE, and I appreciate your feedback.  Please do let me know if either of these fixes solve the problem in your hands.

-Carol Zhou

**Comment by bognabognabogna** [comment]
Thank you Carol. 
Running the code in a conda environment helped indeed!

**Comment by carolzhou** [comment]
I’m so glad. Let me know if you encounter any other issues. Thank you for using multuPhATE.

Sent from my iPhone

On Oct 26, 2019, at 9:01 AM, bognabognabogna <notifications@github.com> wrote:

﻿

Thank you Carol.
Running the code in a conda environment helped indeed!
